### ISSUE TITLE
POST body non-empty for reimageRoleInstanceByDeploymentName and reimageRoleInstanceByDeploymentSlot

### ISSUE THREAD

**Issue by ryan1234** [Azure/azure-sdk-for-node#1189]
The MSDN documentation says the reimage API calls should have no request body for the POST calls.  I changed the generated code in /lib/services/computeManagement/lib/computeManagementClient.js to include &quot;httpRequest.body = null;&quot; inside of beginReimagingRoleInstanceByDeploymentSlot and beginReimagingRoleInstanceByDeploymentSlot and the bug went away.<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1189">https://github.com/Azure/azure-sdk-for-node/issues/1189</a></p>

**Comment by amarzavery** [comment]
closing this as it is too old.

**Comment by ryan1234** [comment]
Bummer. It's been a long time since I tried to use that API call. It was such an easy fix. I wish I could have done it myself.

**Comment by huangpf** [comment]
@ryan1234 
The client code is generated, so it's actually not feasible to modify directly.

@amarzavery 
I think the issue is in the code generator, as in the .NET client, there is no initialization or addition to the  request body field. 

https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/Compute/ComputeManagement/Generated/DeploymentOperations.cs#L2796
