### ISSUE TITLE
Azure require inherits?

### ISSUE THREAD

**Issue by krusk** [Azure/azure-sdk-for-node#1496]
I have the Azure SDK installed in my node project as follows:

    var azure = require('azure');

When I try to run the site (via Visual Studio > Google Chrome), Node throws the error: 

>module.js:338
    throw err;
    ^
>Error: Cannot find module 'inherits'

Does the Azure SDK depend on inherits? And if so, why?

Thanks!
K.

**Comment by jeffwilcox** [comment]
`util.inherits` is a core Node.js concept and utility. Since this is the Azure SDK for Node.js, although you can get close to having it work great in a browser, it is not designed nor tested for that scenario.

You can find out more about `util.inherits` in Node.js here: https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor

And I've seen compatibility code in the past that might unblock you, for example, here: https://github.com/isaacs/inherits

Let me know if that makes sense, @krusk.

SDK team: I recommend closing this issue but will leave it up to your input/response. @mayurid or @devigned ?

**Comment by krusk** [comment]
It does. Thank you.

Kelly

**Comment by devigned** [comment]
Perhaps, take a look at https://github.com/substack/node-browserify#compatibility.

We are working on making the node code isomorphic. You can see some of the work going on in the code generator here: https://github.com/Azure/autorest/pull/421
