### ISSUE TITLE
TypeScript definition for TableResult interface metadata is wrong

### ISSUE THREAD

**Issue by geof90** [Azure/azure-sdk-for-node#1578]
In DefinitelyTyped, the etag is a root level property of the TableResult interface. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-azure/azure.d.ts#L1629

However, from my understanding it should be under a ".metadata" field, i.e `tableResult[".metadata"]["etag"]`.

Tried using the etag from the TableResult in my TypeScript project, it always yields undefined. Casting it to "any" and then getting the etag from the ".metadata" field, e.g. `(<any>tableResult)[".metadata"]["etag"]`, yielded the value needed.

I am not sure who owns the TypeScript definitions on DefinitelyTyped, if it is something I can fix on that repo directly I will gladly help.

**Comment by devigned** [comment]
Thank you for tracking this down! 

I'm not terribly familiar with the DefinitelyTyped repo or the contributors. After a quick scan, it does seem that they take pull requests (http://definitelytyped.org/guides/pull-request.html). I'm sure many others in the community would find value in your contribution if you choose to open a pull request with your fix. Please link back to this issue if you create a pull request in DefinitelyTyped.

I'm going to close the issue here, but if there's anything we can do to assist, please ping back. Cheers!
