### ISSUE TITLE
Documentation site out of date.

### ISSUE THREAD

**Issue by nbering** [Azure/azure-sdk-for-node#1621]
The documentation site published to the `gh-pages` branch is behind the version published to npm, at least for the `azure-arm-compute` module. The package version on npm is `0.14.x` and the docs are stuck at `0.13.0`. I discovered this when my project failed to start after redefining dependencies in my package.json, as the `createComputeManagementClient()` method exposed by the module was no longer present.

**Comment by amarzavery** [comment]
@nbering - I agree. The new version of the azure-arm-compute package has been autogenerated via a new code generator. The client API has changed because of this. We will update the documentation shortly, after the autorest branch is merged into the master branch. Kindly let us know your feedback about the generated code for "0.14.0".

**Comment by nbering** [comment]
@amarzavery I haven't had a chance to upgrade to the new version in my application, yet, but my first impression is that I'm pleased it has type definitions. I spent more time than I would have liked writing interfaces for all the configuration parameters.

**Comment by amarzavery** [comment]
Thanks.
