### ISSUE TITLE
a status code is missing from the error of client.storageAccounts.beginCreate

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-node#1704]
If the account type is wrong in the createParameters of client.storageAccounts.beginCreate, there will be an error without a status code.

For instance, the account type "Stardard_RAGRS" is not a valid value. And I got the below error. 
```
[Error: Error "Stardard_RAGRS is not a valid value for parameters.properties.accountType. The valid values are: ["Standard_LRS","Standard_ZRS","Standard_GRS","Standard_RAGRS","Premium_LRS"]" occurred in serializing the payload - "{ location: 'eastasia', accountType: 'Stardard_RAGRS' }"]
```

My question is:
**When should I expect a status code? When should I not?**

Thanks.

https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/operations/storageAccounts.js#L521

**Comment by amarzavery** [comment]
This error was thrown by the client library. It does the validation, type
Checking and then serializes it.
account type is an enum. Enums are not native to javascript. We have provided an enum like behavior in javascript. The value you provided failed the enum validation and the client threw an error providing adequate information. Since the request was never sent on the wire there is no status code in the error.

Thanks,
Amar Zavery

On Apr 13, 2016, at 8:14 AM, "Bin Xia" <notifications@github.com<mailto:notifications@github.com>> wrote:


If the account type is wrong in the createParameters of client.storageAccounts.beginCreate, there will be an error without a status code.

For instance, the account type "Stardard_RAGRS" is not a valid value. And I got the below error.

[Error: Error "Stardard_RAGRS is not a valid value for parameters.properties.accountType. The valid values are: ["Standard_LRS","Standard_ZRS","Standard_GRS","Standard_RAGRS","Premium_LRS"]" occurred in serializing the payload - "{ location: 'eastasia', accountType: 'Stardard_RAGRS' }"]


My question is:
When should I expect a status code? When should I not?

Thanks.

https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/operations/storageAccounts.js#L521

-

**Comment by bingosummer** [comment]
Thanks @amarzavery .
Got it. That means I should not expect a status code. The error may be from the client library or http response. So I need to check it from my side.

BTW, if there is an example for this in the README of storageManagement2, it would be better. What do you think?

**Comment by amarzavery** [comment]
@bingosummer - I will add one. Thanks for the feedback.
