### ISSUE TITLE
Creating a new notification hub with special characters in the namespace name reports the wrong error

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1720]
Adding special characters to the namespace name (underscores, slashes, square brackets, etc) causes an error to be displayed saying "Namespace already exists. Please enter a different name."

**Comment by amarzavery** [comment]
@danderson00 - It would be nice if you can post the error message. That will help in investigation.
@ankurkul - Can you take a look at this issue?

**Comment by danderson00** [comment]
![image](https://cloud.githubusercontent.com/assets/1265935/14692490/67a09a12-070c-11e6-98e6-8785d0d57c01.png)

**Comment by amarzavery** [comment]
@danderson00 -  This is an error on the portal. It has nothing to do with node sdk. I am not sure about the right avenue for posting errors that happen in the portal. That being said, the notification hubs team can definitely acknowledge this and make sure that it gets fixed in the portal.

Thanks for reporting this.

**Comment by danderson00** [comment]
Well... Of course it is a portal issue... You guys manage your portal blades, right? Or is there a more appropriate place for reporting portal issues?

**Comment by ankurkul** [comment]
@danderson00 : Sure, this looks like a portal error. I have created a work item within our team to address this. Thanks for reporting.

**Comment by amarzavery** [comment]
@ankurkul - Thanks for the prompt response. Please make sure to close this issue once it is resolved.
