### ISSUE TITLE
Appending 30MB file into DataLake Store fails

### ISSUE THREAD

**Issue by avaranovich** [Azure/azure-sdk-for-node#1804]
I am using the following code to append file with the content

``` javascript
var contents = fs.readFileSync('./export/' + item);
 filesystemClient.fileSystem.concurrentAppend('accountname', 'folder/' + item, contents, function (err, result, _, _) {
  if (err) {
   console.log(err);
  } else {
  console.log('result is: ' + util.inspect(result, {depth: null}));
 } });
```

`result is: null
{ [Error]
  statusCode: 404,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'POST',
     headers: 
      { 'x-ms-client-request-id': '6856bdb8-8f1f-456c-96e6-1b408370db77',
        'Transfer-Encoding': 'chunked',
        'accept-language': 'en-US',
        'Content-Type': 'application/octet-stream' },
     url: 'https://xyz.azuredatalakestore.net/WebHdfsExt/adlib%2Fcollect_powerBi_200k.xml?op=CONCURRENTAPPEND&api-version=2015-10-01-preview',
     body: { type: 'Buffer', data: [Object] } },
  response: 
   { body: '',
     headers: 
      { 'x-content-type-options': 'nosniff',
        'strict-transport-security': 'max-age=15724800; includeSubDomains',
        date: 'Tue, 12 Jul 2016 09:38:01 GMT',
        connection: 'close',
        'content-length': '0' },
     statusCode: 404 } }
`

the same happens if I try create. Creating file without the content or with a couple of KB -- works. Hovewer I get 404 while trying 30MB file.

**Comment by amarzavery** [comment]
@begoldsm - Can you take a look at this?
I understand that the node client had issues with performance w.r.t to uploading large files. However, expecting a 404 from the server indicates a different problem.

**Comment by begoldsm** [comment]
@avaranovich @amarzavery this is by design unless you pass in the optional flag concurrentAppend to "createFileIfNotExist" the default for that is false, which is why you are getting a 404, since the file location on the server does not exist yet. To fix this do one of the following:
1. change your existing call to look like this:
var options = {
appendMode: 'autocreate'
};
filesystemClient.fileSystem.concurrentAppend('accountname', 'folder/' + item, contents, options, function...
2. Call filesystemClient.fileSystem.create(accountname, folder/item, function(...)) first.

**Comment by eduardkoller** [comment]
@avaranovich - can you please try the suggested change above, and confirm whether this resolves the issue you were seeing?
