### ISSUE TITLE
Is this project licensed Apache 2 or MIT?

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-sdk-for-node#1837]
Hi,
The `package.json` for the project today says that this project is licensed MIT, but then I see copyright headers in files like this that note it is Apache 2:

https://github.com/Azure/azure-sdk-for-node/blob/master/lib/azure.js#L4

The project was originally Apache 2, afaik, and in the past I did submit an update to the project to conform to newer package.json expectations for license, indicating a continuation of the Apache 2 license at that time:

https://github.com/Azure/azure-sdk-for-node/commit/8d6e7f18e62a910701fb38abf626428b3fbfcdd9

Looks like this commit, a big merge of auto rest, made the license change:

https://github.com/Azure/azure-sdk-for-node/commit/4d219e20714eb81fedd22f6aa539f88a2a339844

Could a maintainer clarify? Thanks!

**Comment by amarzavery** [comment]
We wanted to move from Apache 2 to MIT everywhere in the repo. We shall be making this change across all the service libraries and the roll up sdk in the upcoming sprint.

**Comment by amarzavery** [comment]
@jeffwilcox - I was looking at the [npm documentation](https://docs.npmjs.com/files/package.json#license) to find out the format for licensing. they recommend using an SPDX format. Since we have RDFE client libraries under Apache-2.0 and the Autorest generated libraries under MIT we can have the license value in package.json like this: `"license": "(MIT OR Apache-2.0)",`.

My question is: Since both of them are standard licenses and will be indicated in the above format in package.json, then do we still need a License.txt file in the repo?

**Comment by jeffwilcox** [comment]
Yes, a LICENSE / LICENSE.TXT / LICENSE.MD file is still necessary per open source guidance.

**Comment by amarzavery** [comment]
This should be fixed with the new 1.2.0-preview version of azure.
The repo has two license files. It correctly reflects the license expression in package.json. The README.MD has a license section which lets the user know about the licensing pattern.
