### ISSUE TITLE
Service Bus Subscription read a batch of messages

### ISSUE THREAD

**Issue by davideicardi** [Azure/azure-sdk-for-node#1992]
What is the node.js equivalent of SubscriptionClient.ReceiveBatch?

I see only `receiveSubscriptionMessage`.

**Comment by ZebpayHitesh** [comment]
I am also looking for such service to read multiple messages at once

**Comment by ZebpayHitesh** [comment]
I resolved it through an alternate option.
You can call the `serviceBusService.receiveSubscriptionMessage` method in a callback , so as to call this indefinitely times and make it always listenable.
`function Initiate(callback)
{
	callback();
}
function EndlessMessage(TopicName, SubTopic)
{
	serviceBusService.receiveSubscriptionMessage(TopicName, 'subtopic', function (error, receivedMessage) { // your code}
EndlessMessage(TopicName, SubTopic);}
Initiate(function () {
  // Execute the receiver part
  EndlessMessage(TopicName, subtopic);
});`

**Comment by jtaubensee** [comment]
@davideicardi / @ZebpayHitesh - The Service Bus REST API does not currently support receiving batches, so there is not a valid implementation in this library. Part of the reason is that the REST implementation is not particularly performant, and it is much better to use AMQP. If you are looking for something with better performance, I would take a look at this library: https://github.com/noodlefrenzy/node-amqp10

**Comment by ramya-rao-a** [comment]
Try the `@azure/service-bus` package which has an api to receive messages in batches. This takes the max batch size and max time to wait as input. You will either get the number of messages you asked for or the number of messages that were fetched within the provided time. Checkout the sample that [receives messages in a loop.](https://github.com/Azure/azure-sdk-for-js/blob/%40azure/service-bus_7.0.0/sdk/servicebus/service-bus/samples/javascript/receiveMessagesLoop.js)
