### ISSUE TITLE
Use promises instead of callbacks

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-node#2033]
In 2015 this ticket happened: https://github.com/Azure/azure-sdk-for-node/issues/1450

The answer was a fairly unsubstantiated _callbacks are more common_.  Even for 2015, that was just not in any way accurate.  This continues to be the case today where the `Promise` API is making its way throughout the ecosystem.  Moreover, consistency is almost universally the worst argument to uphold substandard practices.

Given that typescript has implemented `await`, it would be nice to be able to leverage that functionality instead of having to descend into [callback hell](http://callbackhell.com/).

See also:
 - https://github.com/Azure/azure-storage-node/issues/110
 - https://github.com/Azure/azure-documentdb-node/issues/154

**Comment by amarzavery** [comment]
Thanks for the feedback. We are working on it. Will keep you updated.
/cc @balajikris

**Comment by balajikris** [comment]
Hey @atrauzzi This is now fixed with today's update to all our SDKs in this repo. Promises are in, type definitions are refreshed and should work with the latest version of tsc.exe and much more goodness. Check our [latest release here](https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017) and feel free to let us know what you think.

/cc: @amarzavery @fiveisprime
