### ISSUE TITLE
Support for use_ssl_cert?

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-sdk-for-node#2046]
Hey there,
Recently I encountered SSL certificate errors while calling Azure AD graph API using this library:
```
[Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```
Then I looked it up and found this issue: Azure/azure-sdk-for-ruby#493, which seems pretty similar to my issue. The only problem - I couldn't find anything similar to use_ssl_cert in the NodeJS SDK. So, my question is - what can I do?

Thanks!
Omer

**Comment by amarzavery** [comment]
@omerlh - This was inherently a bug in node.js itself. node.js used a static list of trusted certs which were hard coded in code.

with new version of node.js [v4.8.0](https://nodejs.org/dist/latest-v4.x/) or [6.10.0](https://nodejs.org/en/download/), (documentation over [here](https://nodejs.org/docs/latest-v4.x/api/all.html#cli_node_extra_ca_certs_file)) you can set the following environment variable: `set NODE_EXTRA_CA_CERTS=<path-to-pem-file>` and run the commands. This should work fine.

**Comment by omerlh** [comment]
Ok, I do run a bit out of date node version (v 4.5.0). I will try to upgrade. Also - could you provide me the relevant pem file of Azure? I guess I could download it myself, but how often this key will changed?
Thanks,
Omer

**Comment by amarzavery** [comment]
This has got nothing to do with a pem file from Azure. You can generate a system trusted pem file yourself and use it. The lower level handshake does not happen successfully.
If you set this environment variable `set NODE_TLS_REJECT_UNAUTHORIZED=0` then this will pass through.

**Comment by omerlh** [comment]
I already set `NODE_TLS_REJECT_UNAUTHORIZED` as a temporary solution. I probably misunderstood you, but I thought that when you proposed I will use the `set NODE_EXTRA_CA_CERTS=<path-to-pem-file>`, you meant that I should pass Azure Certificate.

**Comment by amarzavery** [comment]
Nope it could be a system generated self signed certificate as well.

**Comment by omerlh** [comment]
Maybe I am missing something - but how this is going to solve this issue?

**Comment by amarzavery** [comment]
Node.js has a static list of trusted cert authorities as can be seen [here](https://github.com/nodejs/node/blob/master/src/node_root_certs.h). If you are behind a corporate proxy or a firewall, it cannot verify the certificate and you get the above error. Hence to solve this issue, node.js provided a mechanism to users where they can provide their own system trusted certs to be added to the static list. node.js should then not fail on certificate verification.

Documentation of the environment variable:

NODE_EXTRA_CA_CERTS=file#

Added in: XXX
When set, the well known "root" CAs (like VeriSign) will be extended with the extra certificates in file. The file should consist of one or more trusted certificates in PEM format. A message will be printed to stderr (once) if the file is missing or misformatted, but any errors are otherwise ignored.

Note that neither the well known nor extra certificates are used when the ca options property is explicitly specified for a TLS or HTTPS client or server.

Take a look at this issue on node.js github repo for more info. https://github.com/nodejs/node/issues/4175.

**Comment by omerlh** [comment]
Yeah, I understand you now. I am not sure this is my issue, but I will try that.
Thanks
