### ISSUE TITLE
Ability to open the default browser instead of asking the user to copy/paste the URL

### ISSUE THREAD

**Issue by am11** [Azure/azure-sdk-for-node#2098]
It would be an improvement if `opn` is considered as a dependency for `ms-rest-azure` package so that it could open the URL in default browser on executing `azure login` from CLI, or upon `msRest.interactiveLogin()` API call. 

https://www.npmjs.com/package/opn

```javascript
const opn = require('opn');
opn('https://aka.ms/devicelogin');
```

**Comment by balajikris** [comment]
That sounds like a nice improvement to have.

**Comment by lostintangent** [comment]
+1 to this. I'm using opn in a project to do exactly this, and it might be nice if the Azure SDK handled this (maybe it could be an opt-in option?).

I'm also parsing out the device code and copying it to the clipboard, which is another behavior that might make sense for the SDK to handle. That way, interactive logins are as simple as possible.

**Comment by amarzavery** [comment]
cool we shall investigate and implement this in the next version if possible.

**Comment by fiveisprime** [comment]
@am11 The SDK module is intentionally left relatively thin due to the varying ways that people will use it. :) We also don't want to force patterns (the "opt-in" action is installing a separate module) and we need to consider browser support.

@lostintangent already built a module that wraps this functionality up and a separate module is the right place for this kind of functionality.

**Comment by PaulieScanlon** [comment]
Hi all, shame this issue is closed. I also think this would be a great idea. 

I understand the concerns about varying ways of using the SDK and browser support but does / could `interactiveLogin` have a sort pre-call hook that contains the `//microsoft.com/devicelogin` url and auth code ... and if like me you want to do something with them you can but be default the cli just logs the instructions as it does now?

Anyone else got any ideas about how to open a browser and copy the code to make it less of a faff for the user?
