### ISSUE TITLE
Service bus data plane type declaration files are out of date

### ISSUE THREAD

**Issue by balajikris** [Azure/azure-sdk-for-node#2099]
@types/azure-sb is missing some service bus definitions:

![image](https://cloud.githubusercontent.com/assets/115199/23829313/e77545e6-06b4-11e7-87f6-3c7f6b160271.png)

I'm also curious, what's the intended usage of this library when it comes to the multiple-sub-packages and `@types` packages?

What combination should I be using?  

 - `@types/azure-sb` and `azure`?  
 - `azure-sb` and `@types/azure-sb`? 
 - `@types/azure` and `azure-sb`?

Forked from https://github.com/Azure/azure-sdk-for-node/issues/2083#issuecomment-285924121 and filing on behalf of @atrauzzi

**Comment by balajikris** [comment]
@jtaubensee and @sazeesha - could you help take a look at this and clarify the customer's question?

**Comment by atrauzzi** [comment]
Thanks @balajikris!

**Comment by jtaubensee** [comment]
@balajikris - I cannot speak to anything regarding the TypeScript definition files, nor can anyone on my team as we didnt actually write the Service Bus portion. I would defer that question to @amarzavery who owns the overall direction of this repo.

**Comment by jtaubensee** [comment]
@balajikris / @atrauzzi - Is this file you are talking about?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/azure-sb/index.d.ts

**Comment by atrauzzi** [comment]
Well, that and just the one registered for the Azure package itself. There's some confusion as to what should be used.

**Comment by pscanf** [comment]
Any news on this?

If you clarify which typings definition should be considered the blessed one ([DefinitelyTyped/azure-sb/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/azure-sb/index.d.ts) vs [DefinitelyTyped/azure/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/azure/index.d.ts)) I could contribute with some definitions.

(I'm guessing that eventually - since `azure-sb` is a "subpackage" of `azure` - `azure`'s typings will just re-export `azure-sb`'s typings, so I would add my definitions to `azure-db`).

**Comment by amarzavery** [comment]
i think your assessment is correct. you should be updating typings of azure-sb

**Comment by despairblue** [comment]
@pscanf Just a heads up that I'm having problems with this as well and like to fix them. `@types/azure-sb` is not imported by `@types/azure`. `@types/azure-sb` does in fact not export anything at all. 

It seems that most definitions are in `@types/azure` itself even though the `azure` package itself seems to be a meta package importing and reexporting [all the smaller ones](https://azure.github.io/azure-sdk-for-node/). It's certainly possible to just install one of it's sub packages and use it.

I wonder if the @types should be structured the same, and also if the types should go to @DefinitelyTyped or here, since a lot of packages already contain type defs in this repo.

**Comment by sledoux** [comment]
Any updates on this? I'm having issues with this as well and probably a lot of people.

Any answer to @despairblue 's questions? I'd like to fix them but need to know where to fix it first.

**Comment by amarzavery** [comment]
Please try out the new servicebus sdk `npm i @azure/service-bus`. The sdk has been moved to https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus . It is developed in TypeScript and contains accurate type definitions.

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
