### ISSUE TITLE
Cannot delete user via AD Graph API client

### ISSUE THREAD

**Issue by BenHall** [Azure/azure-sdk-for-node#2280]
Likewise to #2264

When using the SDK, I can successfully create and list users, however I'm unable to delete them.

My code looks a little bit like this:

```
msRestAzure.loginWithServicePrincipalSecret(user, pass, tenantId, { tokenAudience: 'graph', domain: tenantId}, function (err, graphcredentials) {
  client.users.deleteMethod(user.objectId, function (err) {
    if (err) { console.log("Deleting User Error", err); return cb(err); }
    return cb(null, user.displayName);
  });
});
```

Is there anything I need to add?

**Comment by amarzavery** [comment]
@BenHall - The Graph team told that this is not supported by design. This [link](https://msdn.microsoft.com/en-us/Library/Azure/Ad/Graph/howto/azure-ad-graph-api-permission-scopes#directoryreadwriteall-privileges-detail) provides more info on that. To be able to delete users from a directory one needs to be a user who is a global admin or some kind of Limited Administrator that would have the rights to delete users. You can find out more about the different adminsitrator roles from this [doc](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-assign-admin-roles). The sdk supports creating users, however the role assignment is only supported via portal. This is a one time thing. Then you can login as that user with `msRestAzure.loginWithUsernamePassword()` and you should be able to create as well as delete users from the directory.

**Comment by BenHall** [comment]
Thanks @amarzavery - will update my code accordingly :)

**Comment by BenHall** [comment]
With this being the case, the example in the ReadMe should be updated as it indicates that it's possible - https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/README.md#login-with-serviceprincipal-and-secret
