### ISSUE TITLE
Scheduler jobs with basic authentication cannot be created

### ISSUE THREAD

**Issue by alexanderfilipov** [Azure/azure-sdk-for-node#2347]
Hi there,

I am using the azure-arm-scheduler SDK (version 1.1.0-preview) in order to create scheduled jobs which invoke an HTTP endpoint with Basic authentication:
```
client.jobs.createOrUpdate(resourceGroupName, jobCollectionName, job.name, job)
```

The job object has `properties.action.request.authentication` set to:
```
authentication: {
  type: 'Basic',
  username: 'user',
  password: 'pass'
}
```
but the request fails with `'Username' and 'Password' are required for 'Basic' type of Authentication.`

After some debugging, it seems the serialization mechanism always uses the HttpAuthentication (base class) model instead of BasicAuthentication, so username and password are never sent to the server.
I suspect this could be due to missing polymorphicDiscriminator settings in the serialization models, but I am not sure how it is supposed to be used in this case.

For the moment I've overwritten the HttpRequest model to use BasicAuthentication but it's an ugly hack. Any help would be appreciated.

Thanks,
Alexander

**Comment by amarzavery** [comment]
@alexanderfilipov - Thanks for filing this issue. We auto generate our SDKs from the Open API spec for scheduler service.
The spec says that 
- [the authentication property of the Httpequest object is of type "HttpAuthentication"](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/scheduler/resource-manager/Microsoft.Scheduler/2016-03-01/scheduler.json#L1050)
- Moreover the [HttpAuthentication](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/scheduler/resource-manager/Microsoft.Scheduler/2016-03-01/scheduler.json#L1146) model is not defined as a polymorphic model.
- For languages like C#, python this is ok because
  - they resolve allof as inheritance v/s composition
  - the customer is expected to give an instance of the object in that language(C#/Python/Java). This object could be a child object instead of the parent and the language SDK will happily accept it.
- For node.js, customers are used to providing JSON objects v/s using the `new Foo()` syntax of instantiating JavaScript objects. Thus we need to rely internally on the mapper for [de]serialization.

We shall fix the scheduler spec to make the HttpAuthentication object polymorphic and regenerate and publish a new version of the node sdk.

**Comment by amarzavery** [comment]
@alexanderfilipov - New version (1.2.0-preview) of azure-arm-scheduler with updates to the HttpAuthentication model hierarchy has been published. Let us know if you see further issues.

**Comment by alexanderfilipov** [comment]
Wow, that was quick! Thanks guys, it works as expected!

**Comment by amarzavery** [comment]
Nice to know
