### ISSUE TITLE
Cannot accept agreement -> Signature does not match

### ISSUE THREAD

**Issue by manuelmazzuola** [Azure/azure-sdk-for-node#2423]
I was trying to accept the agreement of the bitnami/cassandra plan.
The result is: `Signature does not match. Please request terms again and request acceptance.`
The code is very simple:
```
const image = await this.azure.virtualMachineImages
 .get('northeurope', 'Bitnami', 'Cassandra', 'Cassandra', '3.11.1709280755');

const agreements = await this.azure.marketplaceAgreements
 .get(image.plan.publisher, image.plan.name, image.plan.product);

if (agreements && !agreements.accepted) {
  agreements.accepted = true;
  await this.azure.marketplaceAgreements
    .create(image.plan.publisher, image.plan.name, image.plan.product, agreements);
}
```

The `await this.azure.marketplaceAgreements.get(image.plan.publisher, 
 mage.plan.name, image.plan.product)` returns 
```
{
id: '/subscriptions/a6dab79e-9b3d-4780-84cb-43a3d4a83d23/providers/Microsoft.MarketplaceOrdering/offertypes/bitnam
i/offers/cassandra/plans/cassandra',
  name: 'cassandra',
  type: 'Microsoft.MarketplaceOrdering/offertypes',
  publisher: 'bitnami',
  product: 'cassandra',
  plan: 'cassandra',
  licenseTextLink: 'https://storelegalterms.blob.core.windows.net/legalterms/3E5ED_legalterms_BITNAMI%253a24CASSAND$
A%253a24CASSANDRA%253a24IGRT7HHPIFOBV3IQYJHEN2O2FGUVXXZ3WUYIMEIVF3KCUNJ7GTVXNNM23I567GBMNDWRFOY4WXJPN5PUYXNKB2QLAKCH
P4IE5GO3B2I.txt',
  privacyPolicyLink: 'https://bitnami.com/privacy',
  retrieveDatetime: 2018-02-16T14:54:37.196Z,
  signature: 'JC5OJJARW7OD6GKOR5HVIE2BTSL5RXW2J7WCNLMDSWNZ3R3R3FN33EGHF5Q5IJHDENLJN4BVBUM733VVOLT3KN5LVH5LHL6T2DSEAX
Q',
  accepted: false
}
```

I've noticed that `retrieveDatetime` is populated but the [documentation says](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js#L199): `Date and time in UTC of when the * terms were accepted. This is empty if Accepted is false.` Could be the problem?

I've also tried to send only the parameters explicitly written in the [documentation](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js#L181) but the result is the same.

**Comment by manuelmazzuola** [comment]
I can not sign the CLA to open a PR because the federated login with GitHub doesn't work.
Here's the fix https://github.com/ClouDesire/azure-sdk-for-node/tree/GH-2423

Seems that the deserialization of the agreements object truncates the `retrieveDatetime`

**Comment by amarzavery** [comment]
I am still trying to understand the problem. 

The service returns `"retrieveDatetime": "2018-02-16T14:54:37.196Z"`. Since the type is specified as "DateTime", we just deserialize it as `new Date("2018-02-16T14:54:37.196Z")` and give it back to you. During serialization, we simply call `.toISOString()` on the provided Date object. 

So how would this truncate anything?

- **deserialization:** [`retrieveDatetime = new Date("2018-02-16T14:54:37.196Z");`](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/serialization.js#L411)

- **serialization:** [`retrieveDatetime = retrieveDatetime instanceof Date ? retrieveDatetime.toISOString(): retrieveDatetime`](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/serialization.js#L360)

**Comment by manuelmazzuola** [comment]
> The service returns "retrieveDatetime": "2018-02-16T14:54:37.196Z

No, the service returns `retrieveDatetime": "2018-02-16T14:54:37.196123Z"` and the client deserialize it to `retrieveDatetime": "2018-02-16T14:54:37.196Z"`.
The milliseconds precision is different.
So, when posting the client uses a different `retrieveDatetime` from the one it received, so the signatures are different.

As I said I cannot submit a PR because the Microsoft portal to sign the CLA doesn't work.
If you decide to implement the fix I suggest to write some tests.

**Comment by amarzavery** [comment]
Cool. The fix makes sense. Since we are autogenerating our sdks from Open API specification of the service, I need to fix this at the source of truth. Seems like python had a similar issue and they stripped out ["format": "date-time" from the parsed spec](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/marketplaceordering/resource-manager#python), thus treating it as a `string`. I shall do this for node.js as well, regenerate the sdk and publish a new version. 

Thanks for providing the context 👍 .

**Comment by amarzavery** [comment]
@manuelmazzuola - `azure-arm-marketplaceordering@1.1.0-preview` has been published. 
NOTE: This will not be a part of the rollup azure package (`require("azure")`) for now. We publish the rollup package less frequently. You can install `"azure-arm-marketplaceordering"` directly and get the latest bits. Thank you for filing the issue and helping us improve the experience for you and other customers.
