### ISSUE TITLE
Retries when using ms-rest-azure and azure-keyvault

### ISSUE THREAD

**Issue by janis91** [Azure/azure-sdk-for-node#3065]
We are using the ms-rest-azure and azure-keyvault package in combination in order to login with an app service "Managed Service Identity" (MSI) on Azure and retrieve a certificate from KeyVault after logged in.
We implemented it in a way, such that everytime our node.js server starts, the MSI is used to create the KeyVaultClient. The client is then used to get the certificate.

```typescript
const credentials = await loginWithAppServiceMSI({ resource: KEY_VAULT_APPLICATION, msiEndpoint: MSI_ENDPOINT, msiSecret: MSI_SECRET });
const keyVaultClient = new azureKeyVault.KeyVaultClient(credentials);
const cert = await keyVaultClient.getCertificate(vault, name, version);
```

A few days ago I stumbled upon some weird dependency traces in ApplicationInsights. Obviously the ``/MSI/token`` and the ``vault.azure.net`` resource / endpoint is called twice. The former with two successful calls. The first vault call resulting in a status 401. Shown in the picture below:

![image](https://user-images.githubusercontent.com/20393872/41919011-cd813d80-795d-11e8-8f88-3b8f68d0d117.png)

I figured out, that every time we restart our application, these logs will be tracked.

I guess the 401 is resulting in a retry inside of the package, but I was wondering, if this is the intended behavior? We do not call the MSI endpoint twice in our code. The KeyVaultClient is created only once and we ``getCertificate()`` only once as well.

Why are there two calls for each of the packages?

**Comment by amarzavery** [comment]
@schaabs and @williexu - Can you guys take a look at this issue?

**Comment by schaabs** [comment]
@janis91 This is expected behavior.  azure-keyvault has an authentication pattern which will always make at least one unauthenticated call to the vault.  This is because some vaults have requirements that messages to them be encrypted with HSM protected keys.  This information is returned in the authentication challenge from the first unauthenticated call.  

For this reason each time you send a request to a vault you haven't connected to yet in that process, the sdk first sends the request with an empty body and without an Authorization header.  This will result in a 401 which will have the authentication and message protocol information.

**Comment by janis91** [comment]
@schaabs Thank you for your answer 👍

Do you also know why a MSI endpoint call with 0 duration is tracked? (Both calls are successful)

**Comment by janis91** [comment]
@amarzavery any idea for the second question?

**Comment by janis91** [comment]
I close this issue, even if it's not answered completely. The question why there is another log entry with 0ms duration for MSI endpoint dependency call, is not that important.
