### ISSUE TITLE
Merge Tables from DataSets into a single file

### ISSUE THREAD

**Issue by cpatte7372** [Azure/azure-sdk-for-node#3865]
Hello Community,

Can someone let me know if its possible to merge / combine the tables from, say SQL server into a single file? With Azure Data Factory

For example, lets say I have TableA and TableB, I would like to merge tables into TableC in a specified destination such as Blob store or Data Lake store.

Cheers

**Comment by kpajdzik** [comment]
We automatically update the Node.js packages based on the OpenAPI specifications in the azure-rest-api-specs repository. As soon as the service team updates their specification, then we will publish a new package. 

In order to suggest this feature the the Data Factory team, please try contacting Azure Support team (https://azure.microsoft.com/en-us/support/options/).
