### ISSUE TITLE
`azure-keyvault` package doesn't export `KeyVaultCredentials` type

### ISSUE THREAD

**Issue by ernieturner** [Azure/azure-sdk-for-node#4820]
When using `azure-keyvault`, being able to create a new instance of the `KeyVaultClient` class requires an instance of the `KeyVaultCredentials` class, as taken from [this example](https://azure.github.io/azure-sdk-for-node/azure-keyvault/latest/). However, when using TypeScript to do this, it doesn't look like the `KeyVaultCredentials` types are exported properly from that package. 

```
import {KeyVaultClient, KeyVaultCredentials} from "azure-keyvault";

const keyVaultClient = new KeyVaultClient(new KeyVaultCredentials(adalCallback));
```

In that example, neither the `KeyVaultCredentials` import nor the `new KeyVaultCredentials` line compile via TypeScript because of the missing types. Instead you have to write it like this to work around the missing types.

```
import * as KeyVault from "azure-keyvault";
const keyVaultClient = new KeyVault.KeyVaultClient(new (KeyVault as any).KeyVaultCredentials(adalCallback));
```

**Comment by amarzavery** [comment]
@schaabs  - Can you take a look at this issue?

**Comment by vagostep** [comment]
Same issue here.

**Comment by amarzavery** [comment]
Thanks for pointing this out. We need to update the README.md and the samples as well.

1. `KeyVaultCredentials` is present inside `ms-rest-azure`, since that is where other credentials are present. Thus `import { KeyVaultCredentials } from "ms-rest-azure"` should work fine.

2. We have made it simpler for you to authenticate. You don't need to worry about challenge callback. We take care of it internally. You can login via one of the `*login*` methods available in `ms-rest-azure` and get the credentials. We shall convert those credentials into `KeyVaultCredentials` for you internally. Thus simplifying the process.

So, the following sample should work.
```typescript
import * as msRestAzure from "ms-rest-azure";
import { KeyVaultClient } from "azure-keyvault";

async function main() {
  try {
    const creds = await msRestAzure.interactiveLogin(); //OR await msRestAzure.loginWithServicePrincipalSecret("clientId", "secret", "domain"); // OR any other login method
    const client = new KeyVaultClient(creds);
    const result = await client.getSecrets("https://<your-kv-account-name>.vault.azure.net");
    console.log(result);
  } catch (err) {
     console.log(err);
  }
}

main();
```
