### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by JTInfinite** [Azure/azure-sdk-for-node#5132]
Similar issue here: https://github.com/Azure/App-Service-Migration-Assistant/issues/15#issue-511627486

In my node project I simply:

`import azure from  'azure-storage'`

and my app now fails to load. I get the following error:

![image](https://user-images.githubusercontent.com/16175334/69349883-765e8d80-0c70-11ea-92ac-fae7ef885023.png)

I had this working a few days ago. It could well be me but just wanted to put it out there.

**Comment by qiaozha** [comment]
@JTInfinite Hi May I know how you use the azure-storage in your app so that I can reproduce this bug and find out where the problem is? 
Also, we are deprecating this repo. You may use @azure/arm-storage instead of azure-storage.if you are trying to manage your Azure resource, 
 depending on how you use azure-storage. please refer to https://github.com/Azure/azure-sdk-for-js repo folder sdk/storage for more information.

**Comment by JTInfinite** [comment]
@qiaozha  Hi, I am getting the error in the browser. To be honest, I think it is something I am doing wrong as I have the exact same module imported fine in another project. I think I am just going to move all my azure resource interaction server side. 

Thanks anyway
