### ISSUE TITLE
Fix the code snippet in the readme for azure-keyvault

### ISSUE THREAD

**Issue by jntrnr** [Azure/azure-sdk-for-node#5153]
Related to: https://github.com/Azure/azure-sdk-for-node/issues/5151

From Ramya: "the sample for [azure-keyvault](https://github.com/Azure-Samples/key-vault-node-authentication), we see KeyvaultCredentials being used for the data plane library, and the normal login methods of ms-rest-azure for the management library. If the login methods of ms-rest-azure cannot be used directly with azure-keyvault, then the [code snippet in the readme](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/keyVault#authentication-and-client-creation) that suggests so should be updated as well. Can you please test this and do the necessary updates?"

**Comment by sadasant** [comment]
I tried to replicate this with my own resources and I haven't been able to do so. So far, azure-sdk-for-node seems to work fine with ms-rest authentication methods. I got in contact with Jon Gallant and he said that he was going to provide me with some specific environment variables that should help me reproduce the bug.

**Comment by ramya-rao-a** [comment]
@sadasant, Can you share which login methods from did you try?

**Comment by sadasant** [comment]
I'll share code snippets as soon as I can go back to this, which should be soon.

**Comment by sadasant** [comment]
Ok so,

What I tried that worked was to use Jon's https://github.com/jongio/storage-node-resource-provider-getting-started

There, Jon uses `KeyVault.msRestAzure.loginWithServicePrincipalSecret` to authenticate.

Since that worked, I tried to reproduce this separately. Here's my isolated code:

```ts
import * as KeyVault from "azure-keyvault";
import * as msRestAzure from "ms-rest-azure";
import { config } from "dotenv";

config();

async function main(): Promise<void> {
  const credentials = await msRestAzure.loginWithServicePrincipalSecret(
    process.env.AZURE_CLIENT_ID,
    process.env.AZURE_CLIENT_SECRET,
    process.env.AZURE_TENANT_ID
  );
  const client = new KeyVault.KeyVaultClient(credentials);
  const keyVaultUrl = `https://${process.env.KEYVAULT_NAME}.vault.azure.net`;
  await client.getKeys(keyVaultUrl);
}

main();
```

That code **fails*. ... But why?

It took me a while, but now I realize that Jon's repo has this definition:

```js
var msRestAzure = require("@azure/ms-rest-nodeauth");
```

Which explains so much 😅

So, yes. Here's a PR updating the readme: https://github.com/Azure/azure-sdk-for-node/pull/5167

**Comment by ramya-rao-a** [comment]
I am not convinced with the fix...

`@azure/ms-rest-nodeauth` was created to support the `@azure/*` libraries. The `azure-*` libraries are meant to use `ms-rest-azure`. The auth parts of `ms-rest-azure` was pulled out  form `@azure/ms-rest-nodeauth`.

We should continue to dig as to why `@azure/ms-rest-nodeauth` works but `ms-rest-azure` doesnt.

**Comment by sadasant** [comment]
Both libraries have a method called `loginWithServicePrincipalSecret` that return a value of the class `ApplicationTokenCredentials`, **however**, these classes are different in `ms-rest-azure` and in `@azure/ms-rest-nodeauth`. I haven't been able to coerce one to become the other yet.

**Comment by sadasant** [comment]
Let's say I try this:

```ts
  const credentials = await msRestAzure.loginWithServicePrincipalSecret(
    process.env.AZURE_CLIENT_ID,
    process.env.AZURE_CLIENT_SECRET,
    process.env.AZURE_TENANT_ID
  );
  const client = new KeyVault.KeyVaultClient(credentials as msRestNodeAuth.ApplicationTokenCredentials);
```

Then I get this error:

```
Argument of type 'ApplicationTokenCredentials' is not assignable to parameter of type 'ServiceClientCredentials'.
  Types of property 'signRequest' are incompatible.
    Type '(webResource: WebResource) => Promise<WebResource>' is not assignable to type '(webResource: WebResource, callback: (err: Error) => void) => void'.
      Types of parameters 'webResource' and 'webResource' are incompatible.
        Type 'WebResource' is missing the following properties from type 'WebResource': withCredentials, timeout, clonets(2345)
```

**Comment by sadasant** [comment]
These two TokenCredentials are widely different:

- https://github.com/Azure/ms-rest-nodeauth/blob/adea8415de97a8076006fbd9948123d09dfdd78d/lib/credentials/tokenCredentialsBase.ts
- https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/credentials/tokenCredentials.js

**Comment by ramya-rao-a** [comment]
>   const client = new KeyVault.KeyVaultClient(credentials as msRestNodeAuth.ApplicationTokenCredentials);

We shouldnt have to cast to ms-rest-nodeauth credentials.
The azure-keyvault package has been around a long time before ms-rest-nodeauth package was created. It shouldnt have to depend on ms-rest-nodeauth at all.

The code snippet in https://github.com/Azure/azure-sdk-for-node/issues/5153#issuecomment-635599921 works fine for me with v2 of ms-rest-azure, but not v3 of ms-rest-azure. Perhaps, we can dig into what happened in v3 that is causing the conflict in types for you?

**Comment by sadasant** [comment]
I cannot make it work in ms-rest-azure v2 nor v3. However, I can make it work with both versions if I pin azure-keyvault to version 3.0.4. I find it always broken in version 3.0.5

**Comment by sadasant** [comment]
The issue is that azure-keyvault 3.0.5 depends on ms-rest-azure 2.6.0, and keeps referencing the 2.6.0 types even if we install ms-rest-azure 3.0.0. This causes the type mismatch. Can we update azure-keyvault to use ms-rest-azure 3.0.0? I tried updating locally, packing azure-keyvault and using that packed tgz, and the issue disappeared.

**Comment by sadasant** [comment]
I believe this issue is similar to https://stackoverflow.com/questions/58840006/multiple-instance-of-same-class-get-different-instanceof

We use instanceof to check if we're receiving the supported credentials. instanceof will answer differently for different classes, even if they have the same name. These classes are instantiated in different places.

This also happens in the browsers with different frames or windows https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof (search for instanceof and multiple context).

I'm looking for a more direct reference of this issue on the Node docs, but so far I've not been able to.

**Comment by ramya-rao-a** [comment]
> We use instanceof to check if we're receiving the supported credentials. instanceof will answer differently for different classes, even if they have the same name. These classes are instantiated in different places.

If this is true, then how does passing credentials from ms-rest-nodeauth to azure-keyvault work? The classes would be different here as well

**Comment by sadasant** [comment]
> how does passing credentials from ms-rest-nodeauth to azure-keyvault work

It doesn't, the names have been confusing me.

It only works if we explicitly use the same version as azure-keyvault (or if NPM makes us use that same version).

**Comment by ramya-rao-a** [comment]
Ok, so I believe the next steps would be
- update readme to note that only v2 of ms rest azure can be used
- update readme with a note on when KeyvaultCredentials should be used instead of the credentials from ms rest azure

Thoughts?

**Comment by sadasant** [comment]
Can do! Thank you 🙌

**Comment by sadasant** [comment]
Here's a PR: https://github.com/Azure/azure-sdk-for-node/pull/5171

**Comment by Dharmvir2020** [comment]
Stay home stay safe
 <a href="https://www.bankingnetwork.online/">Banking network</a>
