### ISSUE TITLE
[Documentation] Authentication documentation error for azure-graph sdk using interactive authentication

### ISSUE THREAD

**Issue by joshlarsen** [Azure/azure-sdk-for-node#5176]
### Error Observed

[Documentation/Authentication.md](/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md) references `tokenAudience` of `graph`, but it should be `https://graph.microsoft.com`. Using `graph` will result in the error below. Using Service Principal Authentication with the subscription and tenant works fine.

```text
AADSTS500011 The resource principal named 'graph' was not found in the tenant named [currentTenantID].
```

<img width="667" alt="Screenshot 2020-06-09 10 24 58" src="https://user-images.githubusercontent.com/2565382/84193302-396db300-aa69-11ea-86e4-4597c0dd740b.png">

### Recommended Fix

Update the following:

```javascript
const AzureGraphClient = require('azure-graph');
const MsRestAzure = require('ms-rest-azure');

const options = {
  tokenAudience: 'graph',
  domain: '<tenantId>' 
};

MsRestAzure.interactiveLogin(options, (err, credentials) => {
  if (err) throw err;

  let graphClient = AzureGraphClient(credentials, '<tenantId>');

  // ..use the client instance to manage service resources.
});
```

To:

```javascript
const AzureGraphClient = require('azure-graph');
const MsRestAzure = require('ms-rest-azure');

const options = {
  tokenAudience: 'https://graph.microsoft.com',
  domain: '<tenantId>' 
};

MsRestAzure.interactiveLogin(options, (err, credentials) => {
  if (err) throw err;

  let graphClient = AzureGraphClient(credentials, '<tenantId>');

  // ..use the client instance to manage service resources.
});
```

**Comment by qiaozha** [comment]
@ramya-rao-a  Hi Ramya, Is azure-graph a data-plane package?

**Comment by ramya-rao-a** [comment]
@willmtemple Can you take a look at this? Based on your prior work in `@azure/graph`, do you recall what the right value to use here would be?

I am hesitant to make this change without due investigation as the use of `graph` for token audience has been documented in a lot of places and there are hard-coded checks for it as well. Relevant PRs
- #2420
- #1922

**Comment by joshlarsen** [comment]
To clarify, `{ tokenAudience: 'https://graph.microsoft.com' }` is only necessary for interactive authentication. Using `{ tokenAudience: 'graph' }` works for Service Principal authentication (and perhaps other methods).

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @joshlarsen 

Interestingly, in the new [@azure/graph](https://www.npmjs.com/package/@azure/graph) package, the readme uses `https://graph.windows.net` as the token audience when doing interactive auth.

@willmtemple should be able to take a look at this next week

**Comment by willmtemple** [comment]
@joshlarsen Thanks for reporting this issue. `graph.microsoft.com` is the endpoint and the resource ID to use for the newer Microsoft Graph API (the package for that API is `@microsoft/microsoft-graph-client` on NPM). The `azure-graph` package is an older package for use with the older Azure Active Directory Graph service (a newer package for this older service exists in `@azure/graph`).

@ramya-rao-a This parameter should definitely be `https://graph.windows.net` and not just `graph`. My intuition is that `https://graph.microsoft.com` will work fine as a resource for generating a token using ADAL, but that token will be rejected by the AAD Graph endpoint for having an incorrect audience. The docs look like they're handwritten, so I think we can just patch them as Josh suggested.

**Comment by ramya-rao-a** [comment]
@joshlarsen, 

Are you using the newer [Microsoft Graph API](https://developer.microsoft.com/graph) or the older [Azure AD Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api)? In case you are planning on moving to the newer Microsoft Graph API, please use the [@microsoft/microsoft-graph-client](https://www.npmjs.com/package/@microsoft/microsoft-graph-client) package instead of `azure-graph` and log any issues you find with it in https://github.com/microsoftgraph/msgraph-sdk-javascript. 

@willmtemple, 

> This parameter should definitely be https://graph.windows.net and not just graph

> The docs look like they're handwritten, so I think we can just patch them as Josh suggested.

My initial concern was all the places in code where `graph` is hard coded. 
But, on taking a deeper look, below are my findings.

Looks like `graph` and `batch` are two valid values for `tokenAudience` which are treated as "shortcuts" to the actual values of `https://graph.windows.net/` and `https://batch.core.windows.net/` respectively.

We see support for this i.e. substitute the shortcuts with the right values in
- [ApplicationTokenCredentials](https://github.com/Azure/azure-sdk-for-node/blob/b157ba84a2e427430db1c75ddabaab72607efdd7/runtime/ms-rest-azure/lib/credentials/applicationTokenCredentials.js#L30-L38)
- [UserTokenCredentials](https://github.com/Azure/azure-sdk-for-node/blob/b157ba84a2e427430db1c75ddabaab72607efdd7/runtime/ms-rest-azure/lib/credentials/userTokenCredentials.js#L14-L22)
- [DeviceTokenCredentials](https://github.com/Azure/azure-sdk-for-node/blob/b157ba84a2e427430db1c75ddabaab72607efdd7/runtime/ms-rest-azure/lib/credentials/deviceTokenCredentials.js#L80-L88)

Looks like when this support was added, the interactive auth workflow got missed. See https://github.com/Azure/azure-sdk-for-node/blob/b157ba84a2e427430db1c75ddabaab72607efdd7/runtime/ms-rest-azure/lib/login.js#L192-L195

So, we can do one of two things
- Update all the docs to use `https://graph.windows.net/` as Josh is suggesting. But then, we will also need to update the if checks in the code where we throw an error if `graph` is passed and a valid tenant value is not such that it works for `https://graph.windows.net/` as well. See https://github.com/Azure/azure-sdk-for-node/blob/b157ba84a2e427430db1c75ddabaab72607efdd7/runtime/ms-rest-azure/lib/credentials/applicationTokenCredentials.js#L102-L105
- Or update the interactive auth workflow to do the substitution for `graph` and `batch` just like it is done in other places

For some history:
- #2420 is when what is being done for `graph` got extended to `batch`

**Comment by joshlarsen** [comment]
@ramya-rao-a,

It's not actually our software. We are integrating a tool that uses [Azure SDK for Node.js](https://azure.github.io/azure-sdk-for-node/), which appears to be fairly old. 

It is using `var msRestAzure = require('ms-rest-azure');` as the basis for all of it's Azure functionality. Unfortunately, we can't really do anything about that.

**Comment by ramya-rao-a** [comment]
@joshlarsen Using `ms-rest-azure` is not the problem here. My question was around using the `azure-graph` package.

The newer [Microsoft Graph API](https://developer.microsoft.com/graph) is recommended over the older [Azure AD Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api).

The `azure-graph` package is for the latter.
The[@microsoft/microsoft-graph-client](https://www.npmjs.com/package/@microsoft/microsoft-graph-client) package is for the former.

Regardless, since you don't have control over the tool that uses `azure-graph` I believe you have no control over moving to Microsoft Graph either.

@willmtemple, I believe we can take the path of least resistance here and just update the docs like @joshlarsen suggested.

**Comment by ramya-rao-a** [comment]
Closing as the docs are now updated with #5187 

Thanks for logging the issue and working with us @joshlarsen!
