### ISSUE TITLE
ms-rest-azure - Specify scope in device cocde login

### ISSUE THREAD

**Issue by jefjos** [Azure/azure-sdk-for-node#5190]
I am using ms-rest-azure for interactive login in a command line application for device code flow - https://github.com/Azure/azure-sdk-for-node/blob/8691046c2ca738552d815f6967f5f54b04840276/runtime/ms-rest-azure/lib/login.js#L153

In this doc on device code flow - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#protocol-diagram the request to /deviceCode endpoint includes scope. However in the interactiveLogin implementation of ms-rest-azure, I do not see a way to specify scope. Without scope, users will not be able to give consent.

**Comment by qiaozha** [comment]
This issue is about ms-rest-azure, @ramya-rao-a  Could you take a look ? Thanks

**Comment by ramya-rao-a** [comment]
Apologies in the delay in response here

The `ms-rest-azure` package uses the [adal-node](https://www.npmjs.com/package/adal-node) package to do the auth work.
From what I can see the `adal-node` package does not allow specifying the scope and hard codes it to `openid` in certain conditions.

I have logged https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/245 for this so that the folks at adal-node can provide answers. Please follow up there
